package com.uuhnaut69.common;

public enum EventType {
  ORDER_CREATED,
  RESERVE_CUSTOMER_BALANCE_SUCCESSFULLY,
  RESERVE_CUSTOMER_BALANCE_FAILED,
  RESERVE_PRODUCT_STOCK_SUCCESSFULLY,
  RESERVE_PRODUCT_STOCK_FAILED,
  COMPENSATE_CUSTOMER_BALANCE
}
