package com.uuhnaut69.common;

public enum SagaStep {
  PLACE_ORDER_REQUEST,
  RESERVE_CUSTOMER_BALANCE_REQUEST,
  RESERVE_CUSTOMER_BALANCE_RESPONSE,
  RESERVE_PRODUCT_STOCK_REQUEST,
  RESERVE_PRODUCT_STOCK_RESPONSE,
  COMPENSATE_CUSTOMER_BALANCE_REQUEST
}
